apiVersion: apps/v1
kind: Deployment
metadata:
  name: moncv
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moncv
  template:
    metadata:
      labels:
        app: moncv
    spec:
      containers:
      - name: moncv
        image: wajditech/cv-onepage:latest
        ports:
        - containerPort: 80
